name: dyna-menu-sys-testing

on: 
  push:
    paths:
      - 'Browser/**'
      - '.github/workflows/test.yml'
    branches:
      - '**'

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Validate
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./Browser
          css: true
          blacklist: ./assets
      - name: Upload log
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: log.log

  lintjs:
    name: Lintjs
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./Browser/
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Lint with ESlint
        run: npx eslint ./
        